apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: taranjeetsingh/api
      context: api
      docker:
        dockerfile: Dockerfile.local
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .