apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: dev.ranjod.com
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 4000