apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - api.ranjod.com
        - app.ranjod.com
      secretName: ranjod-com
  rules:
    - host: api.ranjod.com
      http:
        paths:
          - path: /auth-api/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          - path: /data-api/?(.*)
            backend:
              serviceName: data-srv
              servicePort: 3000
          - path: /assets-api/?(.*)
            backend:
              serviceName: assets-srv
              servicePort: 3000
    - host: app.ranjod.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: dashboard-srv
              servicePort: 3000

