apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - api.blumne.com
        - app.blumne.com
      secretName: ranjod-com
  rules:
    - host: api.blumne.com
      http:
        paths:
          - path: /api/?(.*)
            backend:
              serviceName: api-srv
              servicePort: 4000
    - host: app.blumne.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: dashboard-srv
              servicePort: 3000
---
