export const env = process.env.NODE_ENV;

export const LOCAL_STORAGE_ENV = 'LOCAL_STORAGE_ENV';
export const LOCAL_STORAGE_LANGUAGE = 'LOCAL_STORAGE_LANGUAGE';
export const LOCAL_STORAGE_SELECTED_APPLICATION_NAME = 'LOCAL_STORAGE_SELECTED_APPLICATION_NAME';