apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
        - name: assets
          image: taranjeetsingh/assets
          env:
            - name: MONGO_URI
              value: 'mongodb+srv://all:all@cluster0.a6c0l.mongodb.net/ranjodh?retryWrites=true&w=majority'
              #value: 'mongodb://auth-mongo-srv:27017/authentication'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: assets-srv
spec:
  selector:
    app: assets
  ports:
    - name: assets
      protocol: TCP
      port: 3000
      targetPort: 3000
