apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: taranjeetsingh/data
          env:
            - name: MONGO_URI
              value: 'mongodb://data-mongo-srv:27017/data'
            - name: MONGO_URI_AUTH
              value: 'mongodb://auth-mongo-srv:27017/authentication'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: data-srv
spec:
  selector:
    app: data
  ports:
    - name: data
      protocol: TCP
      port: 3000
      targetPort: 3000

