name: deploy-infra

on:
  push:
    branches:
      - master
    paths: 
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: LOGIN TO DIGITAL OCEAN
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save api-cluster
    - name: APPY MANIFESTS
    - run: kubectl apply -f infra/k8s
