name: deploy-data

on:
  push:
    branches:
      - master
    paths: 
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: AUTH INTO DOCKER
      run: cd data && docker build -t taranjeetsingh/data .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: PUSH TO DOCKER HUB
      run: docker push taranjeetsingh/data
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save ranjod-cluster
    - run: kubectl rollout restart deployment data-depl
